version: "3.8"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - progresDB:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - ./.env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env
    ports:
      - "5050:80"

networks:
  backend:
    driver: bridge

volumes:
  progresDB:
